Repository quiltdata/quilt, pull requests merged in 2018-04, with the labels that each got.

#535 Add 'load' to quilt base module
  compiler/quilt/__init__.py
Labels: quick review

#536 Minor test improvements
  compiler/quilt/test/test_cli.py
  compiler/quilt/test/test_command.py
Labels: quick review, waiting on review

#526 Allow sourcing DataFrames from existing Parquet files
  compiler/quilt/test/test_build.py
  compiler/quilt/tools/build.py
  compiler/quilt/tools/package.py
Labels: waiting on review

#537 build.py uncaught exception fix, other minor misc from export pr
  compiler/quilt/tools/build.py
  compiler/quilt/tools/command.py
  compiler/quilt/tools/const.py
  compiler/quilt/tools/main.py
  compiler/quilt/tools/package.py
  compiler/quilt/tools/store.py
  compiler/quilt/tools/util.py
Labels: waiting on review
